### ISSUE TITLE
json: cannot unmarshal object into Go value of type []*ecs.ContainerDefinition

### ISSUE THREAD

**Issue by michal-adamkiewicz** [cloudposse/terraform-aws-ecs-container-definition#100]
Hey guys,

I guess it's definitely something on my end, but recently I have changed from version 0.23 to latest one (to support TF 0.13).
Based on that unfortunately all my projects starts throwing errors like in title.

Before I had:

```hcl
resource "aws_ecs_task_definition" "task_definition"
{
...
  container_definitions    = module.my_own_name.json
}
```

Now I changed output name accordingly to your documenation like below:

```hcl
resource "aws_ecs_task_definition" "task_definition"
{
...
  container_definitions    = module.my_own_name.json_map_encoded
}
```

But that gives me:
```
ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal object into Go value of type []*ecs.ContainerDefinition
```

Really I would be gratefully for any help

**Comment by flyinprogrammer** [comment]
> container_definitions
is expecting a string, and to be a list, so if you're providing a single definition, you likely want to use:

```
module.my_own_name.json_map_encoded_list
```

**Comment by michal-adamkiewicz** [comment]
Thanks a lot!
