### ISSUE TITLE
Improve interface of the "secrets" input variable

### ISSUE THREAD

**Issue by dvasiljevic-humanity** [cloudposse/terraform-aws-ecs-container-definition#106]
This is a suggestion, very similar to the one already created  in #61 and improvement is closed.

The current way of passing secrets variables to the module is by using a list of maps

```
variable "secrets" {
  type = list(object({
    name      = string
    valueFrom = string
  }))
  description = "The secrets to pass to the container. This is a list of maps"
  default     = null
}

```

eg. with using parameter store

```
secrets = [
    {
      name  = "SECRET_1",
      valueFrom = "arn:aws:ssm:region:aws_account_id:parameter/parameter1_name"
    },
    {
      name  = "SECRET_2",
      valueFrom = "arn:aws:ssm:region:aws_account_id:parameter/parameter2_name"
    }
  ]
```
Hardcoded part of ARN (region and aws_account_id) i guess can be managed dynamically with local variables.
Maybe there can be some refactoring to create `type = map(any)` variable
```
map_secrets = {
      "SECRET_1" = "parameter/parameter1_name"
      "SECRET_2" = "parameter/parameter2_name"
    }
```
Do you think this is possible?

Thanks,
Dejan

**Comment by davidvasandani** [comment]
@dvasiljevic-humanity this PR solved the issue for me. Hope it helps you as well.
