### ISSUE TITLE
Allow to configure volumes

### ISSUE THREAD

**Issue by snowsky** [cloudposse/terraform-aws-ecs-container-definition#113]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

This feature request is to add host volumes to container definition, for example, from https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition:
```
volume {
    name      = "service-storage"
    host_path = "/ecs/service-storage"
  }
```

## Expected Behavior

Local host path can be used to create volumes.

## Use Case

Sometimes the volume parameter is required for container definition and it is supported by Terraform provider. Here is a reference: https://registry.terraform.io/modules/lazzurs/ecs-service/aws/latest?tab=inputs.

**Comment by evanstoddard23** [comment]
Volumes are specified in the task definition, not the container definition.

**Comment by snowsky** [comment]
thanks @evanstoddard23
