### ISSUE TITLE
Output refers to sensitive values

### ISSUE THREAD

**Issue by arnoschutijzer** [cloudposse/terraform-aws-ecs-container-definition#133]
## Describe the Bug
Running `terraform plan` and  `terraform apply` using terraform 0.15.0 results in this error message:
```
│ Error: Output refers to sensitive values
│
│   on .terraform/modules/application.app_container_definition/outputs.tf line 6:
│    6: output "json_map_encoded" {
│
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
```

## Expected Behavior
No error when planning / applying.

## Steps to Reproduce
1. Create a terraform script with a module with `github.com/cloudposse/terraform-aws-ecs-container-definition?ref=0.56.0` as the source
2. Run 'terraform plan'
3. See error

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: MacOS Big Sur
 - Version: 0.15.0

## Additional Context
I think this issue is already fixed on master but there was no release. Can we get this released? We'd like to keep the version locked. EDIT: it's not actually fixed yet. I can give it a go but just marking the outputs as sensitive will be a bit too naive probably. 😄

**Comment by nitrocode** [comment]
Can you expand on your reproducible steps ? What sensitive information are you putting in the module ? Can you remove that information from the module ?

**Comment by nitrocode** [comment]
I'd remove the ssm parameter from the module input, add it to the modules output (the output is simply json) before passing it to the task definition.

**Comment by nitrocode** [comment]
You could also try one of the sensitive outputs

https://github.com/cloudposse/terraform-aws-ecs-container-definition#outputs

**Comment by arnoschutijzer** [comment]
That doesn't work sadly. In the script above I'm not using any outputs of the module so terraform is throwing an error just because the outputs that are not sensitive exist.

**Comment by nitrocode** [comment]
@arnoschutijzer the best way to do this is to use the `map_secrets` or `secrets` input which will make the ecs task retrieve the value from ssm without terraform having to do it.

```hcl
provider "aws" {}

data "aws_ssm_parameter" "some_parameter" {
  name = "/some/path"
}

module "container_definition" {
  source = "github.com/cloudposse/terraform-aws-ecs-container-definition?ref=0.56.0"

  container_image = "nginx"
  container_name = "nginx"

  map_secrets = {
    some_name = data.aws_ssm_parameter.some_parameter.arn
  }
}
```
