### ISSUE TITLE
Terraform 0.15 error when specifying bool input

### ISSUE THREAD

**Issue by darpham** [cloudposse/terraform-aws-ecs-container-definition#136]
## Describe the Bug
After upgrading to Terraform 0.15.x , I'm now getting an error while trying to plan my changes. This seems to relate the the bool flag for readOnly within the mount_points inupt. Switching back to 0.14.x and the issue goes away.

## Expected Behavior
My terraform plan should work with no issues and changes.
`No changes. Infrastructure is up-to-date.`

## Steps to Reproduce
1. Create module with mount_points and specify readOnly bool to true or "true"
2. terraform plan
3. See error
```
  mount_points = [
    {
      containerPath = "/this/path"
      sourceVolume = "this_volume"
      readOnly = <"true" OR true>
    }
  ]
```

## Screenshots
```
Error: ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal string into Go struct field MountPoint.MountPoints.ReadOnly of type bool

with aws_ecs_task_definition.this,
on task_definition.tf line ??, in resource "aws_ecs_task_definition" "this":
83:   container_definitions = jsonencode([
84:     module.application_container_def.json_map_object,
85:   ])
```
## Environment (please complete the following information):
 - OS: OSX 11.1

**Comment by borysbabii** [comment]
the same for me, OSX 11.3.1, Apple M1
```
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.41.0
```

**Comment by borysbabii** [comment]
for some reason it works as expected if you explicitly define variable type like this:
```variable "mount_points" {
  type = list(object({
    containerPath = string
    sourceVolume  = string
    readOnly      = bool
  }))

  description = "Container mount points. This is a list of maps, where each map should contain a `containerPath` and `sourceVolume`. The `readOnly` key is optional."
  default     = []
}```

**Comment by darpham** [comment]
Thanks @borysbabii, I've created a PR to resolve this
https://github.com/cloudposse/terraform-aws-ecs-container-definition/pull/137

**Comment by antdking** [comment]
Is this actually a Terraform bug?
Their [docs]( https://www.terraform.io/docs/language/expressions/types.html#type-conversion) say the conversion should happen (assuming that `jsonencode` is just turning `true` into `"true"`).

I've not seen anything in the Provider/SDK/Terraform changelogs to suggest differently.
