### ISSUE TITLE
ecs_task_definition add support for ephemeral_storage

### ISSUE THREAD

**Issue by haarchri** [cloudposse/terraform-aws-ecs-container-definition#138]
## Describe the Feature

ecs_task_definition add support for ephemeral_storage

## Use Case

use ephemeral_storage 21-200GB in ECS

## Describe Ideal Solution

as of PR approved & merged please add ephemeral_storage https://github.com/hashicorp/terraform-provider-aws/pull/19694

**Comment by haarchri** [comment]
was a fault :/

**Comment by korenyoni** [comment]
@haarchri after doing some development on this module it dawned on me that `ephemeralStorage` is outside the scope of the container definition.

See: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-task-definition.html

What you would actually do is something like this:

```
module "container" {
  source  = "cloudposse/ecs-container-definition/aws"
  version = "0.56.0"
  # insert the 33 required variables here
}

resource "aws_ecs_task_definition" "task" {
  family = "foo"
  container_definitions = module.container.json_map_encoded_list

  ephemeral_storage {
    size_in_gb = 30
  }
}
```

**Comment by ikarlashov** [comment]
@korenyoni Just came across that there's a typo (or value has changed since your publication).
```
resource "aws_ecs_task_definition" "task" {
  family = "foo"
  container_definitions = module.container.json_map_encoded_list

  ephemeral_storage {
    size_in_**gib** = 30
  }
}
```
