### ISSUE TITLE
Feature Request: Support for runtimePlatform

### ISSUE THREAD

**Issue by fdobrovolny** [cloudposse/terraform-aws-ecs-container-definition#153]
## Describe the Feature

I would like to be able to specify `runtimePlatform` to use arm64 arch in fargate tasks.

## Expected Behavior

I'm able to optionally set a map parameter `runtimePlatform`.

## Use Case

https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs-arm64.html

## Additional Context

https://docs.aws.amazon.com/AmazonECS/latest/userguide/task_definition_parameters.html#runtime-platform

**Comment by obataku** [comment]
as you noted, `runtimePlatform` is defined at the _task definition_ level, **not** in the container definitions themselves
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TaskDefinition.html#ECS-Type-TaskDefinition-runtimePlatform

example configuring it on an `aws_ecs_task_definition` resource here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition#example-using-runtime_platform-and-fargate
>```tf
>resource "aws_ecs_task_definition" "test" {
>  ...
>  container_definitions    = <...>
>
>  runtime_platform {
>    operating_system_family = "WINDOWS_SERVER_2019_CORE"
>    cpu_architecture        = "X86_64"
>  }
>}
>```

suggest to close this PR
