### ISSUE TITLE
Support adding tags

### ISSUE THREAD

**Issue by aairey** [cloudposse/terraform-aws-ecs-container-definition#158]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Resources created by this module have no tags.

## Expected Behavior

Have the possibility to pass a set of tags to this module.

## Use Case

Same use-case for having tags in general.

## Describe Ideal Solution

Add a `var.tags` variable consistent with other modules. Add the tags to all taggavle resources in this module.

## Alternatives Considered

/

## Additional Context

/

**Comment by kevcube** [comment]
@aairey this module does not create any resources

**Comment by aairey** [comment]
Right, looks like I will be adding it in the task definition as per the example [here](https://github.com/cloudposse/terraform-aws-ecs-container-definition/blob/master/examples/complete/main.tf).
