### ISSUE TITLE
Log configuration options must all be strings

### ISSUE THREAD

**Issue by tomelliff** [cloudposse/terraform-aws-ecs-container-definition#20]
I was considering trying to use this module to replace an even worse hack that I had for container definitions, particularly around environment variables, but I'm running into an issue with trying to set the log configuration options due to the regex replacing all string quoted integers/booleans with real integers/booleans.

I'm trying to pass something like this:

```hcl
  log_options = {
    "fluentd-async-connect" = "true",
    "fluentd-retry-wait" = "10s",
    "fluentd-max-retries" = "60"
  }
```

But I get the following error on a plan:

> ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal bool into Go struct field LogConfiguration.Options of type string

I'm guessing that I'd need to do something similar to the environment variables and secrets configuration to get this working?

**Comment by alphachai** [comment]
I've been struggling with this for a month or so. Any suggestions would be welcome.

```
  log_driver  = "json-file"
  log_options = {
    "max-size" = "10m"
    "max-file" = "3"
  }
```

```
* module.ecs-service.aws_ecs_task_definition.task_definition: ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal number into Go struct field LogConfiguration.Options of type string
```

**Comment by smiller171** [comment]
I'm running into the same problem. This feels like an AWS provider bug since a jsonencode is already being done...

**Comment by smiller171** [comment]
I found a super shitty workaround

```
log_options = {
    "awslogs-create-group" = <<EOF
\"true\"
EOF
  }
```

**Comment by ReddytoRumble** [comment]
@smiller171 @alphachai Did you end up finding a workaround? I'm running into this as well

**Comment by smiller171** [comment]
I think I ended up just not using this module, but with Terraform 0.12+ maybe you can make the type explicit.

**Comment by alphachai** [comment]
@ReddytoRumble this is working for me right now

```
module "container_definition" {
  source = "github.com/cloudposse/terraform-aws-ecs-container-definition?ref=0.13.0"

  container_name               = "${local.name}"
  container_image              = "${aws_ecr_repository.foobar.repository_url}"
  container_cpu                = "${local.foobar_cpu}"
  container_memory             = 0
  container_memory_reservation = "${local.foobar_memory_reservation}"

  port_mappings = [
    {
      containerPort = "${local.port}"
    },
  ]

  environment = [
    ...
  ]

  log_driver = "json-file"

  log_options = {
    "max-size" = "50m"
  }
}
```

**Comment by tisted-digitalis** [comment]
its still an issue,

"max-size" = "50m" - string
"max-file" = "3" - number
