### ISSUE TITLE
healthcheck.command should accept list of strings

### ISSUE THREAD

**Issue by limitusus** [cloudposse/terraform-aws-ecs-container-definition#33]
I have been using this module from v0.11, and now I'm trying to migrate to v0.12.0.

I hit an issue with the module during migration.
TF says healthcheck attribute's values must all be strings, even as `command` option should accept a list of strings (#31 ).
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_healthcheck

With current `master` branch `healthcheck` variable is declared as a `map`, so the value's type must all be same.

Do you have a good idea for mitigation or need module fix?

## Code

```hcl
module "grpc_envoy" {
  source  = "cloudposse/ecs-container-definition/aws"
  version = "0.13.0"
  healthcheck = {
    command     = ["CMD-SHELL", "grpc_health_probe -addr=localhost:80 || exit 1"]
    retries     = 3
    timeout     = 2
    interval    = 5
    startPeriod = 10
  }
  (snip)
}
```

## Plan result (tf v0.12.0, aws provider v2.11.0)

```
%  terraform plan                                                       

Error: Invalid value for module argument

  on ../module/aws/foo/xxx/task_definition_grpc.tf line 20, in module "grpc_envoy":
  20:   healthcheck = {
  21:     command     = ["CMD-SHELL", "grpc_health_probe -addr=localhost:80 || exit 1"]
  22:     retries     = 3
  23:     timeout     = 2
  24:     interval    = 5
  25:     startPeriod = 10
  26:   }

The given value is not suitable for child module variable "healthcheck"
defined at
.terraform/modules/xxx.grpc_envoy/cloudposse-terraform-aws-ecs-container-definition-c6f5fc3/variables.tf:32,1-23:
all map elements must have the same type.
```

**Comment by aknysh** [comment]
@limitusus  did you get any ideas on how to fix it?

**Comment by limitusus** [comment]
@aknysh 
Just made a PR #34
