### ISSUE TITLE
Support for privileged parameter

### ISSUE THREAD

**Issue by andrewmackett** [cloudposse/terraform-aws-ecs-container-definition#39]
This module doesn't currently support the `privileged` parameter in the container definition.

While I'm aware of the security implications of using `privileged`, it would be a useful addition.

An example of this parameter being required is running a [Falco](https://falco.org/) docker container on ECS hosts to detect anomalous activity: https://falco.org/docs/installation/#docker

I've opened PR https://github.com/cloudposse/terraform-aws-ecs-container-definition/pull/38 to include the `privileged` parameter and tested it with both `EC2` and `FARGATE` launch types.

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-ecs-container-definition/pull/38
