### ISSUE TITLE
Usage with lifecycle

### ISSUE THREAD

**Issue by siassaj** [cloudposse/terraform-aws-ecs-container-definition#43]
# The question
Hi all

We're experiencing a hiccup with terraform infrastructure changes + CD deployments to ECS. CD changes the `container_image` value. There appear to me 3 ways to run terraform without wiping out the changes that CD made.

1. inject the correct docker image tag & string interpolate it into `container_image`
2. get terraform to discover the current `container_image`.
3. use lifecycle & ignore_changes with `container_image`.

Option 1 seems reasonable although 3 seems to be more the correct approach according to [https://www.terraform.io/docs/configuration/resources.html#ignore_changes](https://www.terraform.io/docs/configuration/resources.html#ignore_changes)

On that note, is `lifecycle` supposed to work with this module, if not is it planned, or even possible?

I imagine something like this:

```
lifecycle {
  ignore_changes = [ container_image ]
}
```

That usage returns
```
The block type name "lifecycle" is reserved for use by Terraform in a future
version.
```

Coincidentally `lifecycle` works fine when used with `aws_ecs_task_definition` as such:

```
  lifecycle {
    ignore_changes = [ container_definitions ]
  }
```

However that's not ideal, we need to be able to control things like cpu & memory using terraform.

Thanks for your time & consideration.

# Separately for anyone that's interested

Option 2 has been a failure, I can't find the correct strategy using `data` declarations to get this information, i have tried something like this:

```
data "aws_ecs_container_definition" "www" {
  task_definition = "${aws_ecs_task_definition.default.arn}"
  container_name  = "www"
  depends_on = ["aws_ecs_task_definition.default"]
}

locals {
  www_container_image = coalesce(
    "${data.aws_ecs_container_definition.www.image}",
    "${aws_ecr_repository.default.repository_url}:0.0.1"
    )
}

module "www_container_definition" {
  source = "github.com/cloudposse/terraform-aws-ecs-container-definition"

  container_name = "www"
  container_image = local.www_container_image
  ...
}

resource "aws_ecs_task_definition" "default" {
  family                = "${var.environ_name}"
  container_definitions = "${module.www_container_definition.json}"
  requires_compatibilities = ["FARGATE"]
  network_mode = "awsvpc"
  cpu = 512
  memory = 1024
  execution_role_arn = "${var.task_execution_role_arn}"
}
``` 

However this fails with the following error, that I do not understand (and only guess is due to the circular nature of it all, or maybe I've bungled coalesce).

```
Error: Cycle: module.frontend.module.www_container_definition.output.json, module.frontend.aws_ecs_task_definition.default, module.frontend.data.aws_ecs_container_definition.www, module.frontend.local.www_container_image, module.frontend.module.www_container_definition.var.container_image, module.frontend.module.www_container_definition.local.container_definition, module.frontend.module.www_container_definition.local.encoded_container_definition, module.frontend.module.www_container_definition.local.json_with_environment, module.frontend.module.www_container_definition.local.json_with_secrets, module.frontend.module.www_container_definition.local.json_with_cpu, module.frontend.module.www_container_definition.local.json_with_memory, module.frontend.module.www_container_definition.local.json_with_memory_reservation, module.frontend.module.www_container_definition.local.json_with_stop_timeout, module.frontend.module.www_container_definition.local.json_map
```

**Comment by siassaj** [comment]
If it's helpful to anyone else, I've sorted this problem using the `data "external"` provider in 2 places.

Firstly in the main terraform file to install dependencies:

```
# ./main.tf

data "external" "install_terraform_cloud_deps" {
  program = ["${path.module}/install_terraform_cloud_deps.sh"]
}
```

```
# ./install_terraform_cloud_deps.sh

#!/bin/bash
# Install jq & awscli on Terraform Cloud

set -e

cd ~ &&
mkdir -p ~/.local/bin &&
wget https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip -O ~/awscliv2.zip &&
unzip ~/awscliv2.zip &>/dev/null &&
ln -s ~/aws/dist/aws2 ~/.local/bin/aws &&
wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O ~/.local/bin/jq &&
chmod 0755 ~/.local/bin/jq

~/.local/bin/jq -n --arg status "success" '{ "status": $status }'
```

And then in the submodule that needed the information

```
# ./modules/app_infrastructure/main.tf

data "external" "current_service_image" {
  program = ["${path.module}/get_container_image.sh"]
  query = {
    region = "${data.aws_region.current.name}"
    container = "${local.task_definition_container}"
    family = "${local.task_definition_family}"
    service = "${local.service_name}"
    cluster = "${local.cluster_name}"
  }
}

locals {
  ...
  docker_image = data.external.current_service_image.result.image == "" ? "${aws_ecr_repository.default.repository_url}:LATEST" : 
 data.external.current_service_image.result.image
}
```

```
# ./modules/app_infrastructure/get_container_image.sh

#!/bin/bash

## This script accepts a json object as input and decodes it using JQ, saving the key/vals to ENV
# It then connects to aws ecs and gets the current image for the task definition family and then
# encodes it to json for the module's external data provider to consume.
#
# region: the aws region for this stuff
# container: the task definition container name
# family: the ecs task definition family name
# service: the ecs service name
# cluster: the ecs cluster name

eval "$(~/.local/bin/jq -r '@sh "XREGION=\(.region) XCONTAINER=\(.container) XFAMILY=\(.family) XCLUSTER=\(.cluster) XSERVICE=\(.service)"')"

XREVISION=`~/.local/bin/aws ecs describe-services --cluster $XCLUSTER --services $XSERVICE --region $XREGION | ~/.local/bin/jq '.services[0].taskDefinition' | sed 's/.*:task-definition\/.*\:\(.*\)\"/\1/'`
XIMAGE=`~/.local/bin/aws ecs describe-task-definition --task-definition $XFAMILY:$XREVISION --region $XREGION | ~/.local/bin/jq ".taskDefinition.containerDefinitions[] | select(.name == \"$XCONTAINER\").image" | sed 's/\"\(.*\)\"/\1/'`

~/.local/bin/jq -n --arg image "$XIMAGE" '{ "image": $image }'
```

This is pretty hacky, I wonder if this capability can be ported into this project?

**Comment by nitrocode** [comment]
> On that note, is lifecycle supposed to work with this module, if not is it planned, or even possible?

Lifecycles are reserved in terraform. I understand they apply to resources but I'm unsure if they apply to modules. In the module itself we really don't have any access to how those work... but if there is an issue with that then it would be best to post in the terraform project itself.

> 1. inject the correct docker image tag & string interpolate it into container_image
> 2. get terraform to discover the current container_image.
> 3. use lifecycle & ignore_changes with container_image.

In your CD script, couldn't you retrieve the current task definition, find the image, update it, and register the new task definition outside of terraform? That would be option 1 which is doable. Then you should be able to completely ignore the changes in your container_definitions for your `aws_ecs_task_definition`.

Closing this ticket as there isn't anything we can do. And I don't think adding a hacky solution would be the best way forward. Perhaps if we can retrieve the current task definitions container image using a data source but that would be a separate issue with the terraform aws provider.

**Comment by siassaj** [comment]
@nitrocode Thank you for the review. We ended up with a different approach because like you said a hacky solution isn't appropriate.

The following works quite well without any dependencies or externals, however it's still shy of perfect. I haven't tried to spin up a new env with it, but it works quite well for managing the existing ones.

The cyclic dependency is broken by generating the `task_definition_arn` which is pretty easy:
```
data "aws_region" "current" {}
data "aws_caller_identity" "current" {}
data "aws_ecs_task_definition" "default" {
  task_definition = local.task_definition_family_name
}
data "aws_ecs_container_definition" "default" {
  task_definition = local.generated_task_definition_arn
  container_name  = local.container_name
}

locals {
  task_definition_family_name = "api"
  container_name = "app"
  generated_task_definition_arn = "arn:aws:ecs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:task-definition/${local.task_definition_family_name}:${data.aws_ecs_task_definition.default.revision}"
  docker_image = data.aws_ecs_container_definition.default.image
}
```
