### ISSUE TITLE
Version 0.21 force to have "hostPort" in port_mappings

### ISSUE THREAD

**Issue by magnetik** [cloudposse/terraform-aws-ecs-container-definition#50]
Hi,

I was using the following port_mapping: 

```
  port_mappings = [
    {
      containerPort = 80,
      protocol = "tcp"
    }
  ]
```

As far as I know it's perfectly valid when using the awsvpc networking mode, but latest version 0.21 fails with error: `element 0: attribute "hostPort" is required.`

Something is wrong in the module, right?

Thanks.

**Comment by aknysh** [comment]
@magnetik 
no, eveything is OK with the new version, TF 0.12 has stricter typing, and in the TF 0.12 version the variable is defined as https://github.com/cloudposse/terraform-aws-ecs-container-definition/blob/master/variables.tf#L23

If you don't need any of the fields, set them to `null` (which is supported by TF 0.12)

```
port_mappings = [
    {
      containerPort = 80,
      protocol = "tcp",
     hostPort = null
    }
  ]
```

Whatever is set to `null` TF considers as if it was not provided at all.
Let us know if it fixes the issue
