### ISSUE TITLE
[aws api] Ordering of env vars does not work

### ISSUE THREAD

**Issue by bendavies** [cloudposse/terraform-aws-ecs-container-definition#52]
Hi there,

This is just for visibility here rather than anything.
There is some effort [here](https://github.com/cloudposse/terraform-aws-ecs-container-definition/blob/eee8fbe907b65becbcf338e930d365e71fe3b91d/main.tf#L2-L15) to ensure environment vars are sorted as to not produce unnecessary diffs when any changes are made.

Unfortunately, it doesn't work too well because of a bug in the aws provider:
https://github.com/terraform-providers/terraform-provider-aws/issues/3035

cheers!

**Comment by aknysh** [comment]
@bendavies  thanks for reporting

**Comment by rafilkmp3** [comment]
this force replace all time `module.td.aws_ecs_task_definition.td must be replaced`

**Comment by nitrocode** [comment]
This has been bugging me too. There is currently sorting logic in this module.

https://github.com/cloudposse/terraform-aws-ecs-container-definition/blob/d2e23fdadf1d2615133a338d1b681c78bbe8ed6e/main.tf#L2-L7

If there is an improvement to make this module's `environment` equivalent to the aws api, we'd love to know and pull requests are always welcome.

**Comment by bendavies** [comment]
fixed via https://github.com/terraform-providers/terraform-provider-aws/pull/11463
