### ISSUE TITLE
include a example to create a create log_configuration

### ISSUE THREAD

**Issue by rafilkmp3** [cloudposse/terraform-aws-ecs-container-definition#59]
please include a example to use a log_configuration,  I wasn't able to figure out how  pass to module

**Comment by michelmzs** [comment]
@rafilkmp3 https://github.com/cloudposse/terraform-aws-ecs-container-definition/blob/dea2f1cefaa4702d9b318dda889a5f64407abae7/examples/complete/fixtures.us-east-2.tfvars#L43

**Comment by nitrocode** [comment]
@rafilkmp3 Closing this unless that `log_configuration` example provided above wasn't good enough. Please reopen if that example doesn't satisfy you.
