### ISSUE TITLE
[req] Remove defaults that aren't actually ECS/Fargate defaults

### ISSUE THREAD

**Issue by dekimsey** [cloudposse/terraform-aws-ecs-container-definition#64]
I've run into a few issues where I've left settings unset expecting the default Fargate behavior but been unexpectedly surprised by the selected configuration values.

CPU, memory, reservation, and now port mappings. I appreciate what this module is doing, but setting default values that don't match the ECS service's defaults is surprising behavior.

Thank you!

**Comment by nitrocode** [comment]
If this is still an issue, please feel free to reopen this.
