### ISSUE TITLE
Support new environmentFiles parameter

### ISSUE THREAD

**Issue by andrewmackett** [cloudposse/terraform-aws-ecs-container-definition#70]
AWS announced that ECS supports environment files for the EC2 launch type:
https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-elastic-container-service-supports-environment-files-ec2-launch-type/

I've opened PR #69 to add the new `environmentFiles` parameter to the container definition.

**Comment by btolarz** [comment]
Looks like AWS has some problems with `environmentFiles`
I got in task definition:
`"environmentFiles": null,`

**Comment by nitrocode** [comment]
The PR was merged so this can now be closed.

@btolarz if there is an issue with the module itself, please feel free to open another issue.
