### ISSUE TITLE
log_configuration shouldn't require optional key secretOptions

### ISSUE THREAD

**Issue by Makeshift** [cloudposse/terraform-aws-ecs-container-definition#75]
If you try and define a `log_configuration` block, it will fail if you do not define any `secretOptions`, which are [optional](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html#API_LogConfiguration_Contents).

```
  log_configuration = {
    logDriver = "awslogs"
    options = {
      awslogs-group = aws_cloudwatch_log_group.foo.id
      awslogs-region = var.aws_region
      awslogs-stream-prefix = "db"
    }
  }
```
will throw
```
The given value is not suitable for child module variable "log_configuration"
defined at .terraform\modules\resat_db\variables.tf:135,1-29: attribute
"secretOptions" is required.
```

https://github.com/cloudposse/terraform-aws-ecs-container-definition/blob/master/variables.tf#L149

Setting `secretOptions = []` works around this.

**Comment by nitrocode** [comment]
Sorry, this is still an issue and I opened up a new PR for it.
